# Dark theme for tmux-powerline — reload-safe (no caching guards)

# Use Powerline separators if patched font detected
if tp_patched_font_in_use; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

# Deep dark: bg=233 (#121212), fg=250 (#bcbcbc)
TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR='233'
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR='250'
TMUX_POWERLINE_SEG_AIR_COLOR="37"

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD

# Window list
TMUX_POWERLINE_WINDOW_STATUS_CURRENT=(
	"#[$(tp_format inverse)]"
	"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
	" #I:#W "
	"#[$(tp_format regular)]"
	"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
)
TMUX_POWERLINE_WINDOW_STATUS_STYLE=("$(tp_format regular)")
TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
	"#[$(tp_format regular)]"
	"  #I:#W "
)

# ── Left side: session + git info ──
# 33=blue, 29=dark-teal, 233=near-black, 236=dark-grey
TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
	"tmux_session_info 33 233"
	"vcs_branch 29 236"
)

# ── Right side: host, date, time ──
# 240=grey, 250=soft-white
TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
	"hostname 240 233"
	"date 236 250 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
	"time 236 250 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
)
